# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5691f31fda9883916927efb5d8456a7ef6d5aeea2376f98e3bf1b963ca56bc2b640d69045bb36e069d05b5981fc004a5a8305230da6a6a629368300cc3ad7bd8

test:
  secret_key_base: 00ffae392b2d96b5d3e565beba1d1e538620d54dc2964a7b78b96f19e5fb07b1a2ffc7330684ca20a27410f9c16c886a36cba7bdaf04d4c85d8cdf2d4925d596

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
